//
// Created by jaenster on 15/07/2020.
//

#ifndef D2PacketBased_ENUMS_H
#define D2PacketBased_ENUMS_H

namespace Models {
    namespace UnitType {
        enum UnitType {

            Player,
            Monster,
            Object,
            Missile,
            Item,
            Tile,

            Invalid = 6,
        };
    }

    enum Difficulty : char {
        Normal,
        Nightmare,
        Hell
    };

    namespace Skills {
        enum Type {
            Attack,
            Kick,
            Throw,
            Unsummon,
            LeftHandThrow,
            LeftHandSwing,
            MagicArrow,
            FireArrow,
            InnerSight,
            CriticalStrike,
            Jab,
            ColdArrow,
            MultipleShot,
            Dodge,
            PowerStrike,
            PoisonJavelin,
            ExplodingArrow,
            SlowMissiles,
            Avoid,
            Impale,
            LightningBolt,
            IceArrow,
            GuidedArrow,
            Penetrate,
            ChargedStrike,
            PlagueJavelin,
            Strafe,
            ImmolationArrow,
            Dopplezon,
            Evade,
            Fend,
            FreezingArrow,
            Valkyrie,
            Pierce,
            LightningStrike,
            LightningFury,
            FireBolt,
            Warmth,
            ChargedBolt,
            IceBolt,
            FrozenArmor,
            Inferno,
            StaticField,
            Telekinesis,
            FrostNova,
            IceBlast,
            Blaze,
            FireBall,
            Nova,
            Lightning,
            ShiverArmor,
            FireWall,
            Enchant,
            ChainLightning,
            Teleport,
            GlacialSpike,
            Meteor,
            ThunderStorm,
            EnergyShield,
            Blizzard,
            ChillingArmor,
            FireMastery,
            Hydra,
            LightningMastery,
            FrozenOrb,
            ColdMastery,
            AmplifyDamage,
            Teeth,
            BoneArmor,
            SkeletonMastery,
            RaiseSkeleton,
            DimVision,
            Weaken,
            PoisonDagger,
            CorpseExplosion,
            ClayGolem,
            IronMaiden,
            Terror,
            BoneWall,
            GolemMastery,
            RaiseSkeletalMage,
            Confuse,
            LifeTap,
            PoisonExplosion,
            BoneSpear,
            Bloodgolem,
            Attract,
            Decrepify,
            BonePrison,
            SummonResist,
            IronGolem,
            LowerResist,
            PoisonNova,
            BoneSpirit,
            Firegolem,
            Revive,
            Sacrifice,
            Smite,
            Might,
            Prayer,
            ResistFire,
            HolyBolt,
            HolyFire,
            Thorns,
            Defiance,
            ResistCold,
            Zeal,
            Charge,
            BlessedAim,
            Cleansing,
            ResistLightning,
            Vengeance,
            BlessedHammer,
            Concentration,
            HolyFreeze,
            Vigor,
            Conversion,
            HolyShield,
            HolyShock,
            Sanctuary,
            Meditation,
            FistOfTheHeavens,
            Fanaticism,
            Conviction,
            Redemption,
            Salvation,
            Bash,
            SwordMastery,
            AxeMastery,
            MaceMastery,
            Howl,
            FindPotion,
            Leap,
            DoubleSwing,
            PoleArmMastery,
            ThrowingMastery,
            SpearMastery,
            Taunt,
            Shout,
            Stun,
            DoubleThrow,
            IncreasedStamina,
            FindItem,
            LeapAttack,
            Concentrate,
            IronSkin,
            BattleCry,
            Frenzy,
            IncreasedSpeed,
            BattleOrders,
            GrimWard,
            Whirlwind,
            Berserk,
            NaturalResistance,
            WarCry,
            BattleCommand,
            FireHit,
            Unholybolt,
            Skeletonraise,
            MaggotEgg,
            ShamanFire,
            MagottUp,
            MagottDown,
            MagottLay,
            AndrialSpray,
            Jump,
            SwarmMove,
            Nest,
            QuickStrike,
            Vampirefireball,
            Vampirefirewall,
            Vampiremeteor,
            GargoyleTrap,
            SpiderLay,
            VampireHeal,
            VampireRaise,
            SubMerge,
            FetishAura,
            FetishInferno,
            ZakarumHeal,
            Emerge,
            Resurrect,
            Bestow,
            MissileSkill1,
            MonsterTeleport,
            PrimeLightning,
            PrimeBolt,
            PrimeBlaze,
            PrimeFirewall,
            PrimeSpike,
            PrimeIceNova,
            PrimePoisonBall,
            PrimePoisonNova,
            DiabloLight,
            DiabloCold,
            DiabloFire,
            FingerMageSpider,
            DiabloFirestorm,
            DiabloRun,
            DiabloPrison,
            PoisonBallTrap,
            AndyPoisonBolt,
            HireableMissile,
            DesertTurret,
            ArcaneTower,
            MonsterBlizzard,
            Mosquito,
            Cursedballtrapright,
            Cursedballtrapleft,
            MonsterFrozenArmor,
            MonsterBoneArmor,
            MonsterBoneSpirit,
            MonsterCurseCast,
            HellMeteor,
            RegurgitatorEat,
            MonsterFrenzy,
            QueenDeath,
            ScrollOfIdentify,
            BookOfIdentify,
            ScrollOfTownportal,
            BookOfTownportal,
            Raven,
            PoisonCreeper,
            Werewolf,
            ShapeShifting,
            Firestorm,
            OakSage,
            SummonSpiritWolf,
            WereBear,
            MoltenBoulder,
            ArcticBlast,
            CycleOfLife,
            FeralRage,
            Maul,
            Fissure,
            CycloneArmor,
            HeartOfWolverine,
            SummonDireWolf,
            Rabies,
            FireClaws,
            Twister,
            Vines,
            Hunger,
            ShockWave,
            Volcano,
            Tornado,
            SpiritOfBarbs,
            SummonGrizzly,
            Fury,
            Armageddon,
            Hurricane,
            FireBlast,
            ClawMastery,
            PsychicHammer,
            TigerStrike,
            DragonTalon,
            ShockWeb,
            BladeSentinel,
            BurstOfSpeed,
            FistsOfFire,
            DragonClaw,
            ChargedBoltSentry,
            WakeOfFire,
            WeaponBlock,
            CloakOfShadows,
            CobraStrike,
            BladeFury,
            Fade,
            ShadowWarrior,
            ClawsOfThunder,
            DragonTail,
            LightningSentry,
            WakeOfInferno,
            MindBlast,
            BladesOfIce,
            DragonFlight,
            DeathSentry,
            BladeShield,
            Venom,
            ShadowMaster,
            PhoenixStrike,
            WakeOfDestructionSentry,
            ImpInferno,
            ImpFireball,
            BaalTaunt,
            BaalCorpseExplode,
            BaalMonsterSpawn,
            CatapultChargedBall,
            CatapultSpikeBall,
            SuckBlood,
            CryHelp,
            HealingVortex,
            Teleport2,
            Selfresurrect,
            VineAttack,
            OverseerWhip,
            BarbsAura,
            WolverineAura,
            OakSageAura,
            ImpFireMissile,
            Impregnate,
            SiegeBeastStomp,
            MinionSpawner,
            CatapultBlizzard,
            CatapultPlague,
            CatapultMeteor,
            BoltSentry,
            CorpseCycler,
            DeathMaul,
            DefenseCurse,
            BloodMana,
            InfernoSentry2,
            DeathSentry2,
            SentryLightning,
            FenrisRage,
            BaalTentacle,
            BaalNova,
            BaalInferno,
            BaalColdMissiles,
            MegaDemonInferno,
            EvilHutSpawner,
            CountessFirewall,
            ImpBolt,
            HorrorArcticBlast,
            DeathSentryLightning,
            VineCycler,
            BearSmite,
            Resurrect2,
            BloodLordFrenzy,
            BaalTeleport,
            ImpTeleport,
            BaalCloneTeleport,
            ZakarumLightning,
            VampireMissile,
            MephistoMissile,
            DoomKnightMissile,
            RogueMissile,
            HydraMissile,
            NecromageMissile,
            MonsterBow,
            MonsterFireArrow,
            MonsterColdArrow,
            MonsterExplodingArrow,
            MonsterFreezingArrow,
            MonsterPowerStrike,
            SuccubusBolt,
            MephistoFrostNova,
            MonsterIceSpear,
            ShamanIce,
            DiabloArmageddon,
            Delirium,
            NihlathakCorpseExplosion,
            SerpentCharge,
            TrapNova,
            UnHolyBoltEx,
            ShamanFireEx,
            ImpFireMissileEx,

            Invalid = 0xFFFE,
            None = 0xFFFF,
        };
    }

    namespace TradeType {
        enum TradeType {
            Inventory = 0x00, //: To inventory (buying)
            InventoryFrom = 0x03, //: From inventory/belt (selling, including gambling)
            Belt = 0x04, //: To belt
            Stackable = 0x05,//: To stackable objects (books/keys)
        };
    }

    namespace TradeResult {
        enum TradeResult {
            Purchased = 0x00,// Purchased
            Sold = 0x01,// Sold
            AlreadyTraded_1 = 0x7,// That item has just been traded
            AlreadyTraded_2 = 0x8,// That item has just been traded
            InsufficientSpace = 0xA, //You have not enough space for that
            DontHaveItem = 0xB, //Something tells me that you do not have that item
            InsufficientGold = 0xC,//You have not enough gold for that
            UnavailableNPC = 0xF,//She can't come right now
            MaxAmountMercs = 0x10,// You already have the maximum number of mercs

            // = Other I cannot complete that request
        };
    }

}
;

#endif //D2PacketBased_ENUMS_H
